apiVersion: v1
kind: Service
metadata:
  name: rc-svc
  labels:
    app: rc-svc-lbl
spec:
  type: NodePort
  selector:
    env: qa
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 31200
      protocol: TCP
