apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
  labels:
    app: rc-lbl
spec:
  replicas: 5
  selector:
    env: qa
  template:
    metadata:
      labels:
        env: qa
    spec:
      containers:
        - image: tomcat:9
          name: tomcat-cont
          ports:
            - containerPort: 8080
