apiVersion: v1
kind: Service
metadata:
  name: rs-svc
  labels:
    app: rs-svc-lbl

spec:
  type: NodePort
  selector:
    app: tomcat
    env: qa
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 32400
      protocol: TCP

